//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doc_Appointment_Own_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int appointId { get; set; }
        public int userId { get; set; }
        public int schedulerId { get; set; }
        public System.DateTime appointStart { get; set; }
        public System.DateTime appointEnd { get; set; }
    
        public virtual Scheduler Scheduler { get; set; }
        public virtual User User { get; set; }
    }
}
